before-install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
language: node_js
node_js:
- 0.12
script: |
  ./node_modules/.bin/shortcake test-ci
cache:
  files:
  - BrowserStackLocal
  directories:
  - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: rh3aLhMvUrugv+V1w3ZJxvRQlMH62zGQz02PZDLJFS9k9qe99J/KRIHvsPFw7cQXzDO7uWpX3KKKk+q5qYRF6bskD7n9S10OYnjNe9aDm/rWbiEbjmuWOm1K56C9EjqUCNLygx26Xz9G75qxMqoJDSOMRmwdhbbrwZRo188Pa9OoDuxxHQ7NSSR8MnqRpOXbDBKU1Maxye5WzP3jXxXKmRWP+yx8B76B+74M/NkXrFAyEM0kbJsqBXONeF+WNydftZHwJ1BXPLG3tIzV0PjLcVpBT3HRjgX8aA4775vWurcAwiAgyM6fWRZJRkQnxjPVzY5Ncm2UZMWQFXbd71LB/IzfUIJ5TqdmcVmEQfPOkrhd+eLYoiVte1/lB5Oxg6u4qlMdUVdceWZQfcjQ437q5ZuKKWYn33uFasqAyGOQwhPXdKeOT9lx4uLJ+vCnboRJKmOkx648TrdD9l8/Tl9u0x2Ol3XZPBh1Dj3Xajn5dH4NbQlttH070yvg2xQiWqNVnbqtiGU0uvXbMDJGC2VVFStYCY9k7rOktgSnb0g+sJse/rW63EHr29lSv1/nY/4XYzORQUtrNUMQ2fWWz4OHWAwQ08FvQ9gzLF/oxY5IyTi0UEu5xN8eqZs6cv1Bv4NHQ9M1TWctbQHiEUcBhPV2GQEsjbJZLBXbS2x5Z/ntKSI=
env:
  global:
  - secure: UGhswjJGz7tOJHTcKxrgGZtrP7mBQAFtDFA/52TLxE2SFUS/CoYz9FEt7mouH94Q15jmNN0SmarZwqiLQnIcJgBy5SGDN49S+guQC/IOkH5+PgI8pB7ESMEEZce3Xdwwrut5TENQxCqKbUfSdsisY4vZzrfD5kzzXEcsAP69gpjOvsFPFS9yZRgtAZaqQn9/RaadIj4qFWlNP8TjDhDEGv66NGsua3Ty1QHhji7b3aag+mU8pQNjO6+drwWFyKH7aPzVh4l+ZQhh4QBV11diLaOguHtLRzcKyPGXI+zYWh65n3NmlVTrcWsfyUsPTNfDXVWwQt8RLv6gTZGQRiWLaGWJwzj7upQBYvbq0+DxVIT9j1/qpfwr7Gk7wt/plRNMaU2bHvaek5bRRprZqqOtnXNK3Q3uTQmAU7vtPKX2jcg4llVjdUc8Un4FbK4Ut53q6redSlxdxoJyB/8pVy94K8PJhVXKpPFZO7aInYZqrecjkX0MUUssHaiEbO9okXoT6d86ZMhsEtUp5TkojmvTA6AoKxRrbSOE4sG7DMKMvx+jWZgyYpj0wqv1ZjSZDIElUC6OvPzgfst6iBHu7JnlQTVPTYfjFuCizp61LKnMYiAXF+RwACFnqp4tZSDSsd3FBdWLdUqN/q8fbkJzKYohxyUrp9YzMeBhq9aZrXmjrG0=
  - secure: 0UM1H/vPgiWZgLB0xSTtKP6lL/+sQVAyDhQDr4WP0bvE9b4v+Z9pmOx6XW9KSdwe+wkdKmLBnq0Efvf3WGBgt1t2xxamwu8skc4mBNlvdWoWp6fmnmx/Oru0h+lVDiJLyWdSZkTGh8gRp4GenW/EKHg1+Pp8b2KQjIt1y/DVsfJSBPsiQ8CfSL6l/GT1JBEiggLUtCCHaVSHxEyIF1OMyZkvUhOqGCn6iE7jWjSwA8MgRJJkmhdiYXuL1aXsQmdoKvVlN0+B4I+YobknJ1fRroyioAVJYcE+Pt84CxaiMGItrC8alyPJ9uIpECfrXXy5szMulIkIzGwKngiJCn3rYlHM25TuqLKdmxNvw433UxJLXF93stson5cQImlasg88tgEDtwvV39wvjB7JHDM6zg/fef9FbilkjOjgHx6+PwaSeqMxO3XAKqAiEqKhbmhy+G7TxgJU4Pdrq5lvMHPTD/PGJtTbM8hU/sUrNJkmfxR9fiUIfqTm4HM5EAMZZFu6pE/it9GxrFLueIsg59ITVKR/YL3Mr2TNMlK+EaOdOo5frdYmF18FF41CeAwHYp3GfGivH4dUnkIFDVbbhPYwOkRiDNKr1p5inbpmlUdPABP1G5TSIV3KjJEKclkHGZOwTlx6xSm21AHNMKr8xKHqjYNOS2HjwLrr51iQXVZK8E0=
